networks:
  services_api:
    driver: bridge

services:
### ZMOOZY ###
  instagram_platform:
    image: c5hpiv70.c1.bhs5.container-registry.ovh.net/zmoozy/instagram_platform:1.0.1
    restart: always
    environment:
      SECRET_ACCESS_KEY: 7562c3f6f08f441fb8944c5019d5bf66
      ACCESS_KEY_ID: da2e04cdf0554ebdbb99ceba4dd5b105
      BUCKET_NAME: zmooz-medias
      BASE_URL: https://api.zmoozy.com
      CHECK_PERIOD: 180
      MODEL_SIZE: large-v3
      SESSION_BROWSER: sd6848389redsfl
    expose:
      - 8090
    ports:
      - '8090:8090'
    networks:
      - services_api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

