networks:
  services_api:
    driver: bridge

services:
### ZMOOZY ###
  instagram_platform:
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    image: c5hpiv70.c1.bhs5.container-registry.ovh.net/zmoozy/instagram_platform:1.0.1
    restart: always
    environment:
      SECRET_ACCESS_KEY: 7562c3f6f08f441fb8944c5019d5bf66
      ACCESS_KEY_ID: da2e04cdf0554ebdbb99ceba4dd5b105
      BUCKET_NAME: zmooz-medias
      BASE_URL: https://api.zmoozy.com
      CHECK_PERIOD: 180
      MODEL_SIZE: large-v3
      SESSION_BROWSER: sd6848389redsfl
    expose:
      - 8090
    ports:
      - '8090:8090'
    networks:
      - services_api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


### PROD ###

  refacto-bot-prod-1:
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    image: c5hpiv70.c1.bhs5.container-registry.ovh.net/zmooz/article-bot-storify:2.0.122
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "6"
    environment:
      APP_BASE_URL: https://api.bot-v2.zmooz.com
      BASE_URL: https://api.bot-v2.zmooz.com
      FALLBACK_URL: https://api.bot.zmooz.com
      ENV: PROD
      BOT: BOT_1
      SECRET_ACCESS_KEY: e90bce93b3214c71a0d28f319ea4133f
      ACCESS_KEY_ID: ad3c7daed99d47ca8e0a4b8716b39639
      BUCKET_NAME: zmooz-bucket
      API_SERVICE_URL : bot-service-zmoozy:8081
      TEXT_LIMIT: 180
      SE_KEY: e343b22069ea24c9e
    networks:
      - services_api